name: Docker Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release:
        description: "Release (e.g., v1.9.0)"
        required: true

permissions:
  contents: read

jobs:
  docker-release:
    runs-on: ubuntu-latest
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      RELEASE: ${{ github.event.inputs.release || github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - name: Build Docker Images
        run: make VERSION=${RELEASE:1} DOCKER=coredns -f Makefile.docker release
      - name: Show Docker Images
        run: docker images
      - name: Publish Docker Images
        run: make VERSION=${RELEASE:1} DOCKER=coredns -f Makefile.docker docker-push
