name: Go Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: '1.18.0'
        id: go

      - name: Check out code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          ( cd request; go test -race ./... )
          ( cd core; go test -race  ./... )
          ( cd coremain; go test -race ./... )

  test-plugins:
    name: Test Plugins
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: '1.18.0'
        id: go

      - name: Check out code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Build
        run: go build -v ./...

      - name: Test
        run: ( cd plugin; go test -race ./... )

  test-e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: '1.18.0'
        id: go

      - name: Check out code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          go install github.com/fatih/faillint || true
          ( cd test; go test -race ./... )

  test-makefile-release:
    name: Test Makefile.release
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install make curl

      - name: Check out code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Test Makefile.release
        run: make GITHUB_ACCESS_TOKEN=x -n release github-push -f Makefile.release

      - name: Test Makefile.docker
        run: make VERSION=x DOCKER=x -n release docker-push -f Makefile.docker
